# Generated by Django 4.1.1 on 2022-09-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnlf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='liga',
            name='nombre',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
